/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class compilador_libs_memo_Memory */

#ifndef _Included_compilador_libs_memo_Memory
#define _Included_compilador_libs_memo_Memory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeAlloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_compilador_libs_memo_Memory_nativeAlloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeFree
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeFree
  (JNIEnv *, jclass, jlong);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeWriteInt
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeWriteInt
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeWriteChar
 * Signature: (JC)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeWriteChar
  (JNIEnv *, jclass, jlong, jchar);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeWriteBool
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeWriteBool
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeWriteFloat
 * Signature: (JF)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeWriteFloat
  (JNIEnv *, jclass, jlong, jfloat);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeReadInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_compilador_libs_memo_Memory_nativeReadInt
  (JNIEnv *, jclass, jlong);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeReadChar
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_compilador_libs_memo_Memory_nativeReadChar
  (JNIEnv *, jclass, jlong);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeReadBool
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_compilador_libs_memo_Memory_nativeReadBool
  (JNIEnv *, jclass, jlong);

/*
 * Class:     compilador_libs_memo_Memory
 * Method:    nativeReadFloat
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_compilador_libs_memo_Memory_nativeReadFloat
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
